/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.wecache.GUIs;

import com.mycompany.wecache.BaseClasses.Cache;
import com.mycompany.wecache.Info.JsonHandler;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;


/**
 *
 * @author User
 */
public class CacheSearchWindow extends JFrame
{
    
    Cache selectedCache;
    HashSet<Cache> caches;
    HashSet<Cache> waitlist;

    /**
     * Creates new form CacheSearchWindow
     */
    public CacheSearchWindow() throws UnsupportedEncodingException, IOException
    {
        
        initComponents();
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        caches = new HashSet();
        waitlist = new HashSet();
        
        updateCaches();
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_Cache = new javax.swing.JList<String>();
        checkBox_Waitlist = new javax.swing.JCheckBox();
        label_Address = new javax.swing.JLabel();
        button_SelectCache = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        label_LatLong = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        label_SearchRadius = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        button_Search = new javax.swing.JButton();
        button_ClearFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        list_Cache.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_CacheValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_Cache);

        checkBox_Waitlist.setText("View Waitlist Caches");
        checkBox_Waitlist.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBox_WaitlistStateChanged(evt);
            }
        });

        label_Address.setText("Address");

        button_SelectCache.setText("Select Cache");
        button_SelectCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SelectCacheActionPerformed(evt);
            }
        });

        label_LatLong.setText("Lat/Long Coordinates");

        label_SearchRadius.setText("Search Radius");

        button_Search.setText("Search");

        button_ClearFilter.setText("Clear Filter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBox_Waitlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_SelectCache, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_LatLong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4)
                    .addComponent(button_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label_SearchRadius))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(button_ClearFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBox_Waitlist)
                        .addGap(65, 65, 65)
                        .addComponent(label_Address)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_LatLong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(label_SearchRadius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_Search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_ClearFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_SelectCache, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBox_WaitlistStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBox_WaitlistStateChanged
        updateCaches();
    }//GEN-LAST:event_checkBox_WaitlistStateChanged

    private void list_CacheValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_CacheValueChanged
        Object name = list_Cache.getSelectedValue();
        
        if (name != null)
        {
            if (checkBox_Waitlist.isSelected())
            {
                Iterator<Cache> values = waitlist.iterator();
                selectedCache = values.next();

                while (values.hasNext() && !selectedCache.toString().equals(name.toString()))
                {
                    selectedCache = values.next();
                }
            }
            else
            {
                Iterator<Cache> values = caches.iterator();
                selectedCache = values.next();

                while (values.hasNext() && !selectedCache.toString().equals(name.toString()))
                {
                    selectedCache = values.next();
                }
            }
        }
        
        //System.out.println(selectedCache);
    }//GEN-LAST:event_list_CacheValueChanged

    private void button_SelectCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SelectCacheActionPerformed
        if (selectedCache != null)
        {
            MainWindow.getSingleton().changeCache(selectedCache);
        }
    }//GEN-LAST:event_button_SelectCacheActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ClearFilter;
    private javax.swing.JButton button_Search;
    private javax.swing.JButton button_SelectCache;
    private javax.swing.JCheckBox checkBox_Waitlist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel label_Address;
    private javax.swing.JLabel label_LatLong;
    private javax.swing.JLabel label_SearchRadius;
    private javax.swing.JList<String> list_Cache;
    // End of variables declaration//GEN-END:variables

    private void updateCaches()
    {
        if (checkBox_Waitlist.isSelected())
        {
            waitlist = new HashSet();
            DefaultListModel model = new DefaultListModel();
            ArrayList<Cache> newCaches = JsonHandler.retrieveWaitlistCaches();
            
            for (Cache c : newCaches)
            {
                waitlist.add(c);
                model.addElement(c);
            }
            
            list_Cache.setModel(model);
            
        }
        else
        {
            caches = new HashSet();
            DefaultListModel model = new DefaultListModel();
            List<Cache> newCaches = JsonHandler.retrieveAvailableCaches();
            
            for (Cache c : newCaches)
            {
                caches.add(c);
                model.addElement(c);
            }
            
            list_Cache.setModel(model);
        }
        
    }
    
}
